#Developpement docker-compose file by Nayren
version: '3.8'

services:

  #This container is used to store the data
  microservice_db:
    container_name: microservice_db
    image: postgres
    restart: always

    environment:
      POSTGRES_PASSWORD: nayren123
      POSTGRES_USER: rayan
      POSTGRES_DB: rayan
    volumes:
      - ./postgres-data:/var/lib/postgresql/data #data storage, to keep the data after the container is stopped (need to create the folder before if not exist)
    ports:
      - "5433:5432"

  #This container is used to get the pgadmin
  uniride_pgadmin:
    container_name: uniride_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "80:80"
    depends_on:
      - microservice_db
    
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "nayren"


x-environment:
  COMPOSE_PROJECT_NAME: microservice_nayren